config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  root "restaurants#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews do
      resources :endorsements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ActionController::Base.helpers.image_path("https://s9.postimg.org/4oq3qc9vz/pexels_photo_132464.jpg")
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :reviews,
      -> { extending WithUserAssociationExtension },
      dependent: :destroy
  belongs_to :user
  validates :name, length: { minimum: 3 }, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
  belongs_to :user
  belongs_to :restaurant
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
  has_many :endorsements

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :restaurants
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include?(restaurant)
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.user_id == current_user.id
      flash[:notice] = 'You did not create this restaurant, troll'
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user_id == current_user.id
      @restaurant.update(restaurant_params)
    else
      flash[:notice] = 'You did not create this restaurant, troll'
    end
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user_id == current_user.id
      @restaurant.destroy
      flash[:notice] = "Restaurant deleted successfully"
    else
      flash[:notice] = 'You did not create this restaurant, troll'
    end
      redirect_to restaurants_path
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :review_owner, only: [:edit, :update, :destroy]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)

    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        if user_signed_in?
          redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
        else
          redirect_to new_user_session_path, alert: "For heaven's sake will you sign in already"
        end
      else
        render :new
      end
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to restaurants_path
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = 'Review deleted successfully'
    redirect_to restaurants_path
  end

  private

  def review_owner
    @review = Review.find(params[:id])
    unless @review.user_id == current_user.id
      flash[:notice] = 'You did not create this review'
      redirect_to restaurants_path
    end
  end

  def review_params
    params.require(:review).permit(:thoughtsandfeelings, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    rating = rating.round
    remainder = (5 - rating)
    "★" * rating + "☆" * remainder.ceil
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
  %link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous")
  %link(rel="stylesheet"type="text/css" href="style.css")
  %meta(charset="UTF-8")
    %title CrowdReview
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body

  %header
    %div(id="Title" class="clip-text")
      %h2
        = link_to "CrowdReview", root_path, class: 'title-header'
    %div(id='Sign_in_links')
      - if user_signed_in?
        = link_to "Sign out", destroy_user_session_path, method: :Delete
      - else
        = link_to "Sign in", new_user_session_path
        = link_to "Sign up", new_user_registration_path
        = link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path
  %div(id='content')
    = notice
    = alert
    = yield

app/views/restaurants/_form.html.haml
= form_for @restaurant, html: {multipart: true} do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_field :description
  = f.file_field :image
  = f.submit

app/views/restaurants/edit.html.haml
= render "form"

app/views/restaurants/index.html.haml
%div(id='AddRestaurant')
  %h3= link_to "Add a restaurant", new_restaurant_path
- if @restaurants.any?
  %div(id='row')
    - @restaurants.each do |restaurant|
      %div(id='restaurant' class="col-sm-6 col-md-4")
        %div(id='restaurant_label')
          %h4= link_to restaurant.name, restaurant_path(restaurant)
        %div(class='frame-square')
          %div(class='crop')
            = link_to restaurant_path(restaurant) do
              = image_tag restaurant.image.url, size: "150x150"
        %div(id='restaurant_body')
          %br
          %i= restaurant.description
          - if restaurant.average_rating.is_a? String
            %h5 AVERAGE RATING: N/A
            %p There are no reviews for this establishment yet. Why not leave the first?
          - else
            %h5 AVERAGE RATING: #{restaurant.average_rating.round(1)}
            #{star_rating(restaurant.average_rating)}
            %p= "Based on #{restaurant.reviews.count} reviews."
          %p= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
          - if current_user
            - if current_user.id === restaurant.user_id
              %h5= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
              %h5= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete


- else
  No restaurants yet

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= render "form"

app/views/restaurants/show.html.haml
%h2= @restaurant.name
%h5= @restaurant.description

- if @restaurant.average_rating.is_a? String
  %h5 AVERAGE RATING: N/A
- else
  %h5 AVERAGE RATING: #{@restaurant.average_rating.round(1)}
  #{star_rating(@restaurant.average_rating)}
%h2
  Reviews
- @restaurant.reviews.each do |review|
  %ul
    %b Review:
    = review.thoughtsandfeelings
    %b Rating:
    = star_rating(review.rating)
    %span.endorsements-count= review.endorsements.count
    = 'endorsement'.pluralize review.endorsements.count
    - if user_signed_in?
      = link_to "Endorse", restaurant_review_endorsements_path(@restaurant, review), class: 'endorsements-link'
      -if (current_user.id == review.user_id)
        = link_to "Edit Review", edit_restaurant_review_path(@restaurant, review)
        = link_to "Delete Review", restaurant_review_path(@restaurant, review), method: :delete


%h5= link_to "Review #{@restaurant.name}", new_restaurant_review_path(@restaurant)

app/views/reviews/edit.html.haml
= form_for @review, url: {action: "update"} do |f| 
  = f.label :thoughtsandfeelings
  = f.text_area :thoughtsandfeelings
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Update Review'

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughtsandfeelings
  = f.text_area :thoughtsandfeelings
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'

app/views/reviews/show_review.html.haml
%p= @restaurant.name
%p= @restaurant.review